server:
  port: 8000
spring:
  application:
    name: service-provider
  jpa:
    properties:
      hibernate: 
        cache: 
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: true
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
#    schema: classpath:schema.sql
#    data: classpath:data.sql
logging:
  level:
    root: info    
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka 
  instance:
    prefer-ip-address: true
  